### ISSUE TITLE
Is AICc method necessary?

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#19]
Check with Ben Bolker if bbmle::AICc can be tweaked to work with fitsad and fitrad objects. Currently a tweaked version of the method is in the packe sads.

**Comment by andrechalom** [comment]
Instead of this, can't we simply add a "df" attribute to the fitsad/fitrad objects?

**Comment by andrechalom** [comment]
Still on this issue, it seems that AICc (as well as bbmle's) is not doing its work properly because it silently expects nobs to be declared - except when more than one object is passed, in which case it stops with an error:

```R
> g <- fitgs(okland)
> bbmle::AICc(g)
numeric(0)
> AIC(g)
[1] 7760.35
> AICc(g)
numeric(0)
> AICc(g, g)
Error in AICc(g, g) : must specify number of observations
```

On the other hand, the AIC method for class mle2, when called with more than one argument, enforces that all objects must be exactly of class mle2, so it might be a good idea to reimplement those methods:
```R
> AIC(g)
[1] 7760.35
> AIC(g, g)
Error in AIC(g, g) : all objects in list must be class mle2
```

**Comment by piklprado** [comment]
1 - Sure adding a 'df' attribute for numebr of free parameters is the right choice
2 - I also agree to reimplement AIC & friends methods to accept more than one objetc of class sad or rad.

**Comment by andrechalom** [comment]
OK: some OOP theory here.

We can define a `setMethod("AIC","mle2", ...)` instead of copying the code for fitsad and fitrad classes, and this method will be applied for all objects that inherit from mle2 - including fitsad and fitrad. It is important to keep this method consistent with `bbmle` methods, so people may use `AIC(mle2(...))` and get the same result as doing `bbmle::AIC(mle2(...))`. The methods I'm implementing check for `inherits(x, "mle2")`, so they will work on all objects.

1. These methods required an explicit implementation of `nobs` for fitsad and fitrad:
```R
> nobs(fitgamma(okland))
[1] 21
> nobs(fitgs(okland))
[1] 21
> length(okland)
[1] 21
```

2. `AIC(mle2)` redirects the actual computation for `AIC(logLik)`. I would love to do the same with AICc, but the code for `AICc(logLik)` includes a FIXME, so I'm reimplementing the calculations. Everything works as expected:
```R
> AICc(fitgs(okland), fitmand(okland))
      AICc df
1 7758.561  1
2 7756.373  2
```

3. I did not implement a "df" attr in the fit[sr]ad classes, as it can be easily acquired by `attr(logLik(x), "df")`.
4. As the methods for AIC(mle2), AICc(mle2) are now in the global namespace, it seems that ICtab is correctly using them instead of their bbmle conterparts. I was very happily surprised by this:
```R
> AICctab(fitgs(okland), fitmand(okland))
                dAICc df
fitmand(okland) 0.0   2 
fitgs(okland)   0.2   1 
```

It is important to note that these methods do not differentiate between fitsad and fitrad objects, so the user must take care in not mixing them. However, errors like this will probably be very conspicuous:
```R
> AICctab(fitgs(okland), fitgamma(okland))
                 dAICc df
fitgamma(okland)    0  2 
fitgs(okland)    7534  1 
```

**Comment by piklprado** [comment]
Ok. Let's just include a warning note in the vignette.
